---
extends: default

rules:
  line-length: disable
  truthy: disable
  document-start: disable
  comments:
    min-spaces-from-content: 1
  comments-indentation: disable

ignore: |
  .venv/
  .esphome/
  esphome/.esphome/
  esphome/secrets.yaml
