#!/usr/bin/env python3
"""
Embed GD32 firmware binary and flash assets as C headers for standalone OTA.

Reads firmware/gd32/build/gd32_firmware.bin (and optionally flash_assets.bin)
and generates C header array in esphome/custom_components/htram_gd32/embedded_gd32_firmware.h.
"""

import sys
import zlib
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
GD32_BIN = REPO_ROOT / "firmware" / "gd32" / "build" / "gd32_firmware.bin"
ASSETS_BIN = REPO_ROOT / "firmware" / "gd32" / "build" / "flash_assets.bin"
HEADER_OUT = REPO_ROOT / "esphome" / "custom_components" / "htram_gd32" / "embedded_gd32_firmware.h"


def format_hex_array(data: bytes, indent: str = "  ", per_line: int = 16) -> str:
    lines = []
    for i in range(0, len(data), per_line):
        chunk = data[i : i + per_line]
        hex_str = ", ".join(f"0x{b:02x}" for b in chunk)
        if i + per_line < len(data):
            lines.append(f"{indent}{hex_str},")
        else:
            lines.append(f"{indent}{hex_str}")
    return "\n".join(lines)


def main():
    if not GD32_BIN.exists():
        print(f"Error: {GD32_BIN} not found. Run 'make gd32' first.", file=sys.stderr)
        return 1

    fw_data = GD32_BIN.read_bytes()
    fw_crc = zlib.crc32(fw_data) & 0xFFFFFFFF
    fw_len = len(fw_data)

    print(f"Embedding GD32 firmware: {fw_len} bytes, CRC32: 0x{fw_crc:08X}")

    has_assets = ASSETS_BIN.exists()
    assets_data = ASSETS_BIN.read_bytes() if has_assets else b""
    assets_crc = (zlib.crc32(assets_data) & 0xFFFFFFFF) if has_assets else 0
    assets_len = len(assets_data)

    if has_assets:
        print(f"Embedding Graphic Assets: {assets_len} bytes, CRC32: 0x{assets_crc:08X}")

    content = f"""// Auto-generated by tools/embed_gd32_firmware.py - DO NOT EDIT MANUALLY
#pragma once
#include <cstdint>
#include <cstddef>

#ifdef HTRAM_ENABLE_EMBEDDED_GD32

static constexpr uint32_t EMBEDDED_GD32_FW_CRC32 = 0x{fw_crc:08X}U;
static constexpr size_t EMBEDDED_GD32_FW_LEN = {fw_len};

static const uint8_t EMBEDDED_GD32_FW_DATA[{fw_len}] = {{
{format_hex_array(fw_data)}
}};

"""

    if has_assets:
        content += f"""static constexpr uint32_t EMBEDDED_GD32_ASSETS_CRC32 = 0x{assets_crc:08X}U;
static constexpr size_t EMBEDDED_GD32_ASSETS_LEN = {assets_len};

static const uint8_t EMBEDDED_GD32_ASSETS_DATA[{assets_len}] = {{
{format_hex_array(assets_data)}
}};
"""

    content += """
#endif  // HTRAM_ENABLE_EMBEDDED_GD32
"""

    HEADER_OUT.write_text(content, encoding="utf-8")
    print(f"Generated {HEADER_OUT}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
