substitutions:
  name: htram
  friendly_name: HTRAM

esphome:
  name: ${name}
  friendly_name: ${friendly_name}

esp32:
  board: esp32dev
  framework:
    type: esp-idf
    advanced:
      minimum_chip_revision: "3.0"
      sram1_as_iram: true

logger:
  baud_rate: 115200

api:
  encryption:
    key: !secret api_key
  services:
    - service: beep
      variables:
        freq: int
        dur: int
      then:
        - lambda: |-
            id(htram_core)->send_beep(freq, dur);
            
    - service: set_backlight
      variables:
        brightness: int
      then:
        - lambda: |-
            id(htram_core)->send_backlight(brightness);

    - service: set_leds
      variables:
        r: int
        y: int
        g: int
        brightness: int
      then:
        - lambda: |-
            id(htram_core)->send_leds(r, y, g, brightness);

    - service: enter_bootloader
      then:
        - lambda: |-
            id(htram_core)->send_enter_bootloader();

ota:
  - platform: esphome
    password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: "${friendly_name} Setup"

captive_portal:

external_components:
  - source: custom_components

uart:
  id: uart_bus
  tx_pin: GPIO17
  rx_pin: GPIO16
  baud_rate: 115200

htram_gd32:
  id: htram_core
  uart_id: uart_bus

sensor:
  - platform: wifi_signal
    name: "WiFi RSSI"
    update_interval: 30s
  - platform: uptime
    name: "Uptime"
  - platform: htram_gd32
    co2:
      name: "CO2"
    temperature:
      name: "Temperature"
    humidity:
      name: "Humidity"
    battery:
      name: "Battery Voltage"

text_sensor:
  - platform: version
    name: "ESPHome Version"
